apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/muratozcubukcu/terrahelm.git
    targetRevision: main
    path: helm/argocd
    helm:
      values: |
        argocd:
          server:
            ingress:
              enabled: true
              hosts:
                - argocd.local
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
        
        postgresql:
          enabled: true
          auth:
            postgresPassword: "argocd123"
            database: "argocd"
            username: "argocd"
            password: "argocd123"
          primary:
            persistence:
              enabled: true
              size: "10Gi"
              storageClass: "standard"
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
        
        argocd:
          redis:
            enabled: true
            auth:
              enabled: false
        
        rbac:
          create: true
        
        serviceAccount:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 