apiVersion: v1
kind: Namespace
metadata:
  name: terrahelm
  labels:
    app.kubernetes.io/name: terrahelm
    app.kubernetes.io/part-of: terrahelm-stack
    argocd.argoproj.io/managed-by: argocd

---
apiVersion: v1
kind: Secret
metadata:
  name: terrahelm-db-secret
  namespace: terrahelm
  labels:
    app.kubernetes.io/name: terrahelm
    app.kubernetes.io/part-of: terrahelm-stack
data:
  POSTGRES_HOST: cG9zdGdyZXNxbC50ZXJyYWhlbG0uc3ZjLmNsdXN0ZXIubG9jYWw=
  POSTGRES_PORT: NTQzMg==
  POSTGRES_DB: YXBwZGI=
  POSTGRES_USER: YXBwdXNlcg==
  POSTGRES_PASSWORD: YXBwcGFzc3dvcmQ=
type: Opaque