{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "backend.fullname" . }}-redis
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    component: redis
spec:
  serviceName: {{ include "backend.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
      component: redis
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
        component: redis
      {{- with .Values.redis.master.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command:
            - redis-server
            - /etc/redis/redis.conf
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          env:
            {{- if .Values.redis.auth.enabled }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.redis.master.resources | nindent 12 }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: redis-config
          configMap:
            name: {{ include "backend.fullname" . }}-redis-config
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: {{ .Values.redis.master.persistence.accessModes }}
        storageClassName: {{ .Values.redis.master.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.redis.master.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-redis-master
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    component: redis
spec:
  type: {{ .Values.redis.master.service.type }}
  ports:
    - port: {{ .Values.redis.master.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
    component: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-redis-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    component: redis
data:
  redis.conf: |
    # Redis configuration
    bind 0.0.0.0
    port 6379
    {{- if .Values.redis.auth.enabled }}
    requirepass {{ .Values.redis.auth.password }}
    {{- end }}
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes
    timeout 0
    tcp-keepalive 300
    loglevel notice
    logfile ""
    databases 16
    always-show-logo yes
    set-proc-title yes
    proc-title-template "{title} {listen-addr} {server-mode}"
    supervised no
    pidfile /var/run/redis_6379.pid
    tcp-backlog 511
    unixsocket /tmp/redis.sock
    unixsocketperm 700
    syslog-enabled no
    syslog-ident redis
    syslog-facility local0
    databases 16
    latency-monitor-threshold 0
    notify-keyspace-events ""
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    stream-node-max-bytes 4096
    stream-node-max-entries 100
    activerehashing yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    hz 10
    dynamic-hz yes
    aof-rewrite-incremental-fsync yes
    rdb-save-incremental-fsync yes
    lfu-log-factor 10
    lfu-decay-time 1
{{- end }} 