apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.app.name }}-reader
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "simple-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.app.name }}-reader-binding
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "simple-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.app.name }}-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }} 