apiVersion: v2
name: backend
description: Backend application with statefulset
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - backend
  - statefulset
  - postgresql
  - redis
maintainers:
  - name: DevOps Team
    email: devops@example.com 