apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cronjobs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-repo
    targetRevision: main
    path: helm-charts/cronjobs
  destination:
    server: https://kubernetes.default.svc
    namespace: my-project-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 