apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-custom.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-custom.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.argocd.server.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "argocd-custom.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "argocd-custom.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "argocd-custom.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: argocd-server
        image: "{{ .Values.global.imageRegistry | default "quay.io" }}/argoproj/argocd:{{ .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        args:
        - argocd-server
        - --insecure
        - --staticassets
        - /shared/app
        - --repo-server
        - {{ include "argocd-custom.fullname" . }}-repo-server:8081
        - --redis
        - {{ include "argocd-custom.fullname" . }}-redis:6379
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8080
          protocol: TCP
        env:
        - name: ARGOCD_API_SERVER_REPLICAS
          value: "{{ .Values.argocd.server.replicas | default 1 }}"
        - name: ARGOCD_SERVER_REPLICAS
          value: "{{ .Values.argocd.server.replicas | default 1 }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 6
        resources:
          {{- toYaml .Values.argocd.server.resources | nindent 10 }}
        volumeMounts:
        - name: static-assets
          mountPath: /shared/app
      volumes:
      - name: static-assets
        emptyDir: {} 