apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argocd-custom.fullname" . }}-cm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-custom.labels" . | nindent 4 }}
data:
  # Argo CD configuration
  url: "https://{{ .Values.argocd.server.ingress.hosts | first }}"
  
  # Database configuration
  database.host: "{{ include "argocd-custom.postgresqlServiceName" . }}"
  database.port: "5432"
  database.name: "{{ .Values.postgresql.auth.database }}"
  database.user: "{{ .Values.postgresql.auth.username }}"
  
  # Redis configuration
  redis.host: "{{ include "argocd-custom.fullname" . }}-redis"
  redis.port: "6379"
  
  # Repository configuration
  repos: |
    - type: git
      url: https://github.com/argoproj/argocd-example-apps
      insecure: true
  
  # Application settings
  application.controller.replicas: "1"
  application.server.replicas: "1"
  application.repoServer.replicas: "1" 