{{- if .Values.argocd.server.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "argocd-custom.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-custom.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.argocd.server.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.argocd.server.ingress.ingressClassName }}
  {{- if .Values.argocd.server.ingress.tls }}
  tls:
    {{- range .Values.argocd.server.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.argocd.server.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- range $.Values.argocd.server.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "argocd-custom.fullname" $ }}-server
                port:
                  number: {{ .port | default 443 }}
          {{- end }}
    {{- end }}
{{- end }} 