apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-custom.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-custom.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    {{- include "argocd-custom.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server 