{{- if .Values.cacheClear.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: advanced-cache-clear
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 4 * * *"  # Daily at 4 AM
  workflowSpec:
    templates:
    - name: cache-clear-main
      dag:
        tasks:
        - name: clear-redis
          template: clear-redis-cache
        - name: clear-argo
          template: clear-argo-cache
    
    - name: clear-redis-cache
      container:
        image: redis:7-alpine
        command: [sh, -c]
        args:
        - |
          echo "Clearing Redis cache..."
          redis-cli -h {{ include "argocd-custom.fullname" . }}-redis -p 6379 FLUSHALL
          echo "Redis cache cleared successfully"
    
    - name: clear-argo-cache
      container:
        image: alpine:3.18
        command: [sh, -c]
        args:
        - |
          echo "Clearing Argo CD cache..."
          # Add Argo CD cache clearing logic here if needed
          echo "Argo CD cache cleared successfully"
{{- end }} 