{{- if .Values.cacheClear.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: advanced-cache-clear
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 4 * * *"  # Daily at 4 AM
  workflowSpec:
    arguments:
      parameters:
      - name: cache-type
        value: "all"  # Options: redis, argo, system, all
      - name: dry-run
        value: "false"
    templates:
    - name: cache-clear-main
      dag:
        tasks:
        - name: check-cache-type
          template: determine-cache-type
        - name: clear-redis
          template: clear-redis-cache
          when: "{{ .Values.cacheClear.cacheType | default 'all' }} == 'redis' || {{ .Values.cacheClear.cacheType | default 'all' }} == 'all'"
        - name: clear-argo
          template: clear-argo-cache
          when: "{{ .Values.cacheClear.cacheType | default 'all' }} == 'argo' || {{ .Values.cacheClear.cacheType | default 'all' }} == 'all'"
    
    - name: determine-cache-type
      script:
        image: alpine:3.18
        command: [sh]
        source: |
          echo "Cache type to clear: {{ .Values.cacheClear.cacheType | default 'all' }}"
          echo "Dry run mode: {{ .Values.cacheClear.dryRun | default 'false' }}"
    
    - name: clear-redis-cache
      container:
        image: redis:7-alpine
        command: [sh, -c]
        args:
        - |
          if [ "{{ .Values.cacheClear.dryRun | default 'false' }}" = "true" ]; then
            echo "DRY RUN: Would clear Redis cache"
          else
            redis-cli -h {{ include "argocd-custom.fullname" . }}-redis -p 6379 FLUSHALL
            echo "Redis cache cleared"
          fi
{{- end }}