apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-custom.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-custom.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc }}
  postgres-user: {{ .Values.postgresql.auth.username | b64enc }}
  postgres-database: {{ .Values.postgresql.auth.database | b64enc }} 