apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-custom.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-custom.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.postgresql.primary.service.type }}
  ports:
  - port: {{ .Values.postgresql.primary.service.port }}
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    {{- include "argocd-custom.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database 